version: "3.9"

services:
  api:
    build: .
    container_name: relaxena-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

  worker:
    build: .
    container_name: relaxena-worker
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: relaxena-redis
    ports:
      - "6379:6379"
